import { type Database, schema } from "@plumas/db";
import { count, desc, eq } from "drizzle-orm";

const { media, users } = schema;

export interface CreateMediaInput {
  // Generated by the caller (not left to the column's own defaultRandom()) so the same id can
  // be used as the R2 key prefix before the row exists - see apps/web's upload route.
  id: string;
  ownerId: string;
  r2Key: string;
  width: number;
  height: number;
  albumId?: string | null;
  postId?: string | null;
}

export async function createMedia(database: Database, input: CreateMediaInput) {
  const [row] = await database
    .insert(media)
    .values({ ...input, albumId: input.albumId ?? null, postId: input.postId ?? null })
    .returning();
  if (!row) throw new Error("Failed to create media row");
  return row;
}

/** FR-FEED-01: the upload route's 10-image-per-post cap. */
export async function countPostMedia(database: Database, postId: string): Promise<number> {
  const [row] = await database
    .select({ value: count() })
    .from(media)
    .where(eq(media.postId, postId));
  return row?.value ?? 0;
}

/** Scoped to userId by every caller - never a client-supplied id. */
export async function setUserAvatar(database: Database, userId: string, avatarKey: string) {
  await database.update(users).set({ avatarKey }).where(eq(users.id, userId));
}

export async function setUserCover(database: Database, userId: string, coverKey: string) {
  await database.update(users).set({ coverKey }).where(eq(users.id, userId));
}

export async function listUserMedia(database: Database, ownerId: string) {
  return database
    .select()
    .from(media)
    .where(eq(media.ownerId, ownerId))
    .orderBy(desc(media.createdAt));
}
